[preview]
syntax_highlighting_theme = "Catppuccin Mocha"

[editor_open]
command = "nvim --server $NVIM --remote-send '<cmd>close<cr><cmd>lua OpenFromExternal(\"e\", \"%file\", %line)<CR>'"

[search]
disable_prepopulated_fields = false

[keys.general]
quit = "C-q"
reset = "C-r"
show_help_menu = "C-?"
